package Autenticazione;

import java.util.ArrayList;
import java.util.List;

public class NazioniGenerator
{
    private ArrayList<String> listaNazioni = new ArrayList<String>();

    public ArrayList<String> getListaNazioni()
    {
        return listaNazioni;
    }
    public NazioniGenerator()
    {
        listaNazioni.add("Afghanistan");
        listaNazioni.add("Albania");
        listaNazioni.add("Algeria");
        listaNazioni.add("Andorra");
        listaNazioni.add("Angola");
        listaNazioni.add("Anguilla");
        listaNazioni.add("Antigua e Barbuda");
        listaNazioni.add("Arabia Saudita");
        listaNazioni.add("Argentina");
        listaNazioni.add("Armenia");
        listaNazioni.add("Aruba");
        listaNazioni.add("Australia");
        listaNazioni.add("Austria");
        listaNazioni.add("Azerbaigian");
        listaNazioni.add("Bahamas");
        listaNazioni.add("Bahrain");
        listaNazioni.add("Bangladesh");
        listaNazioni.add("Barbados");
        listaNazioni.add("Belgio");
        listaNazioni.add("Belize");
        listaNazioni.add("Benin");
        listaNazioni.add("Bermuda");
        listaNazioni.add("Bhutan");
        listaNazioni.add("Bielorussia");
        listaNazioni.add("Birmania");
        listaNazioni.add("Bolivia");
        listaNazioni.add("Bosnia ed Erzegovina");
        listaNazioni.add("Botswana");
        listaNazioni.add("Brasile");
        listaNazioni.add("Brunei");
        listaNazioni.add("Bulgaria");
        listaNazioni.add("Burkina Faso");
        listaNazioni.add("Burundi");
        listaNazioni.add("Cambogia");
        listaNazioni.add("Camerun");
        listaNazioni.add("Canada");
        listaNazioni.add("Capo Verde");
        listaNazioni.add("Ceuta");
        listaNazioni.add("Ciad");
        listaNazioni.add("Cile");
        listaNazioni.add("Cina");
        listaNazioni.add("Cipro");
        listaNazioni.add("Città del Vaticano");
        listaNazioni.add("Afghanistan");
        listaNazioni.add("Colombia");
        listaNazioni.add("Comore");
        listaNazioni.add("Corea del Nord");
        listaNazioni.add("Corea del Sud");
        listaNazioni.add("Costa d'Avorio");
        listaNazioni.add("Costa Rica");
        listaNazioni.add("Croazia");
        listaNazioni.add("Cuba");
        listaNazioni.add("Curaçao");
        listaNazioni.add("Danimarca");
        listaNazioni.add("Dominica");
        listaNazioni.add("Ecuador");
        listaNazioni.add("Egitto");
        listaNazioni.add("El Salvador");
        listaNazioni.add("Emirati Arabi Uniti");
        listaNazioni.add("Eritrea");
        listaNazioni.add("Estonia");
        listaNazioni.add("Etiopia");
        listaNazioni.add("Fær Øer");
        listaNazioni.add("Figi");
        listaNazioni.add("Filippine");
        listaNazioni.add("Finlandia");
        listaNazioni.add("Francia");
        listaNazioni.add("Gabon");
        listaNazioni.add("Gambia");
        listaNazioni.add("Georgia");
        listaNazioni.add("Georgia del Sud e Isole Sandwich Australi");
        listaNazioni.add("Germania");
        listaNazioni.add("Ghana");
        listaNazioni.add("Giamaica");
        listaNazioni.add("Giappone");
        listaNazioni.add("Gibilterra");
        listaNazioni.add("Gibuti");
        listaNazioni.add("Giordania");
        listaNazioni.add("Grecia");
        listaNazioni.add("Grenada");
        listaNazioni.add("Groenlandia");
        listaNazioni.add("Guadalupa ");
        listaNazioni.add("Guam");
        listaNazioni.add("Guatemala");
        listaNazioni.add("Guinea");
        listaNazioni.add("Guinea Equatoriale");
        listaNazioni.add("Guinea-Bissau");
        listaNazioni.add("Guyana");
        listaNazioni.add("Guyana francese ");
        listaNazioni.add("Haiti");
        listaNazioni.add("Honduras");
        listaNazioni.add("Hong Kong");
        listaNazioni.add("India");
        listaNazioni.add("Indonesia");
        listaNazioni.add("Iran");
        listaNazioni.add("Iraq");
        listaNazioni.add("Irlanda");
        listaNazioni.add("Islanda");
        listaNazioni.add("Isole Canarie");
        listaNazioni.add("Isole Cayman");
        listaNazioni.add("Isole Cocos e Keeling");
        listaNazioni.add("Isole Cook");
        listaNazioni.add("Isola di Natale");
        listaNazioni.add("Isole Falkland");
        listaNazioni.add("Isole Marianne Settentrionali");
        listaNazioni.add("Isole Marshall");
        listaNazioni.add("Isola Norfolk");
        listaNazioni.add("Isole Pitcairn");
        listaNazioni.add("Isole Salomone");
        listaNazioni.add("Isole Sparse dell'oceano Indiano");
        listaNazioni.add("Isole Vergini americane");
        listaNazioni.add("Isole Vergini britanniche");
        listaNazioni.add("Israele");
        listaNazioni.add("Italia");
        listaNazioni.add("Kazakistan");
        listaNazioni.add("Kenya");
        listaNazioni.add("Kirghizistan");
        listaNazioni.add("Kiribati");
        listaNazioni.add("Kuwait");
        listaNazioni.add("Laos");
        listaNazioni.add("Lesotho");
        listaNazioni.add("Lettonia");
        listaNazioni.add("Libano");
        listaNazioni.add("Liberia");
        listaNazioni.add("Libia");
        listaNazioni.add("Liechtenstein");
        listaNazioni.add("Lituania");
        listaNazioni.add("Lussemburgo");
        listaNazioni.add("Macao");
        listaNazioni.add("Macedonia del Nord");
        listaNazioni.add("Madagascar");
        listaNazioni.add("Madera");
        listaNazioni.add("Malawi");
        listaNazioni.add("Maldive");
        listaNazioni.add("Malesia");
        listaNazioni.add("Mali");
        listaNazioni.add("Malta");
        listaNazioni.add("Marocco");
        listaNazioni.add("Martinica");
        listaNazioni.add("Mauritania");
        listaNazioni.add("Mauritius");
        listaNazioni.add("Mayotte");
        listaNazioni.add("Melilla");
        listaNazioni.add("Messico");
        listaNazioni.add("Moldavia");
        listaNazioni.add("Mongolia");
        listaNazioni.add("Montenegro");
        listaNazioni.add("Montserrat");
        listaNazioni.add("Mozambico");
        listaNazioni.add("Namibia");
        listaNazioni.add("Nauru");
        listaNazioni.add("Nepal");
        listaNazioni.add("Nicaragua");
        listaNazioni.add("Niger");
        listaNazioni.add("Nigeria");
        listaNazioni.add("Niue");
        listaNazioni.add("Norvegia");
        listaNazioni.add("Nuova Caledonia");
        listaNazioni.add("Nuova Zelanda");
        listaNazioni.add("Oman");
        listaNazioni.add("Paesi Bassi");
        listaNazioni.add("Pakistan");
        listaNazioni.add("Palau");
        listaNazioni.add("Stato di Palestina");
        listaNazioni.add("Panama");
        listaNazioni.add("Papua Nuova Guinea");
        listaNazioni.add("Paraguay");
        listaNazioni.add("Perù");
        listaNazioni.add("Polinesia Francese");
        listaNazioni.add("Polonia");
        listaNazioni.add("Porto Rico");
        listaNazioni.add("Portogallo");
        listaNazioni.add("Principato di Monaco");
        listaNazioni.add("Qatar");
        listaNazioni.add("Regno Unito");
        listaNazioni.add("Repubblica Ceca");
        listaNazioni.add("Repubblica Centrafricana");
        listaNazioni.add("Repubblica del Congo");
        listaNazioni.add("Repubblica Democratica del Congo");
        listaNazioni.add("Repubblica Dominicana");
        listaNazioni.add("Riunione");
        listaNazioni.add("Romania");
        listaNazioni.add("Ruanda");
        listaNazioni.add("Russia");
        listaNazioni.add("Saint Kitts e Nevis");
        listaNazioni.add("Saint Vincent e Grenadine");
        listaNazioni.add("Saint-Barthélemy");
        listaNazioni.add("Saint-Martin");
        listaNazioni.add("Saint-Pierre e Miquelon");
        listaNazioni.add("Samoa");
        listaNazioni.add("Samoa Americane");
        listaNazioni.add("San Marino");
        listaNazioni.add("Saint Lucia");
        listaNazioni.add("Sant'Elena, Ascensione e Tristan da Cunha");
        listaNazioni.add("São Tomé e Príncipe");
        listaNazioni.add("Senegal");
        listaNazioni.add("Serbia");
        listaNazioni.add("Seychelles");
        listaNazioni.add("Sierra Leone");
        listaNazioni.add("Singapore");
        listaNazioni.add("Sint Maarten");
        listaNazioni.add("Siria");
        listaNazioni.add("Slovacchia");
        listaNazioni.add("Slovenia");
        listaNazioni.add("Somalia");
        listaNazioni.add("Spagna");
        listaNazioni.add("Sri Lanka");
        listaNazioni.add("Stati Federati di Micronesia");
        listaNazioni.add("Stati Uniti d'America");
        listaNazioni.add("Sudafrica");
        listaNazioni.add("Sudan");
        listaNazioni.add("Sudan del Sud");
        listaNazioni.add("Suriname");
        listaNazioni.add("Svezia");
        listaNazioni.add("Svizzera");
        listaNazioni.add("Swaziland");
        listaNazioni.add("Tagikistan");
        listaNazioni.add("Taiwan");
        listaNazioni.add("Tanzania");
        listaNazioni.add("Thailandia");
        listaNazioni.add("Timor Est");
        listaNazioni.add("Togo");
        listaNazioni.add("Tokelau");
        listaNazioni.add("Tonga");
        listaNazioni.add("Trinidad e Tobago");
        listaNazioni.add("Tunisia");
        listaNazioni.add("Turchia");
        listaNazioni.add("Turkmenistan");
        listaNazioni.add("Turks e Caicos");
        listaNazioni.add("Tuvalu");
        listaNazioni.add("Ucraina");
        listaNazioni.add("Uganda");
        listaNazioni.add("Ungheria");
        listaNazioni.add("Uruguay");
        listaNazioni.add("Uzbekistan");
        listaNazioni.add("Vanuatu");
        listaNazioni.add("Venezuela");
        listaNazioni.add("Vietnam");
        listaNazioni.add("Wallis e Futuna");
        listaNazioni.add("Yemen");
        listaNazioni.add("Zambia");
        listaNazioni.add("Zimbabwe");
    }
}
